<?php

namespace app\widgets;

use yii\base\Widget;

class Button extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        // return the html
        parent::run(); // TODO: Change the autogenerated stub
        return '<button class="btn btn-dark">Click Me</button>';
    }
}