<?php

namespace app\widgets;

use yii\base\Widget;

class Button extends Widget
{
    public $text = '';
    public function init()
    {
        // do all the logic 
        // will run first
        $this->text = ucfirst($this->text);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {


        // return the html
        parent::run(); // TODO: Change the autogenerated stub
        return '<button class="btn btn-dark">' . $this->text . '</button>';
    }
}
